CREATE SEQUENCE user_id_seq START WITH 0 INCREMENT BY 1 MINVALUE=0 CYCLE;
CREATE TABLE user (
	id	VARCHAR(255)	NOT NULL,
	email	VARCHAR(200) NOT NULL,
	pwd	VARCHAR(300)	NOT NULL,
	name	VARCHAR(300) NOT NULL
);
