CREATE SEQUENCE user_id_seq START WITH 0 INCREMENT BY 1 MINVALUE=0 CYCLE;
        
CREATE TABLE user
(
  id    VARCHAR(20)  NOT NULL COMMENT '아이디',
  email VARCHAR(200) NOT NULL COMMENT '이메일',
  pwd   VARCHAR(300) NOT NULL COMMENT '비밀번호',
  name  VARCHAR(300) NOT NULL COMMENT '이름',
  PRIMARY KEY (id, email)
) COMMENT '유저테이블';

      